apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-25T01:15:59Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "4349"
  uid: 0f83386a-30ba-44c4-a5d9-4fdcb4223a49
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.190.62
  clusterIPs:
  - 10.0.190.62
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30840
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.219.66.102
      ipMode: VIP
